<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Моя корзина");?>

<?$APPLICATION->IncludeComponent(
	"bitrix:sale.basket.basket", 
	".default", 
	[
		"COLUMNS_LIST" => [
			0 => "NAME",
			1 => "DISCOUNT",
			2 => "PROPS",
			3 => "DELETE",
			4 => "DELAY",
			5 => "PRICE",
			6 => "QUANTITY",
			7 => "SUM",
			8 => "IN_STOCK",
		],
		"PATH_TO_ORDER" => "/personal/order/make/",
		"HIDE_COUPON" => "Y",
		"PRICE_VAT_SHOW_VALUE" => "N",
		"COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
		"USE_PREPAYMENT" => "N",
		"QUANTITY_FLOAT" => "Y",
		"SET_TITLE" => "Y",
		"ACTION_VARIABLE" => "action",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "24",
		"OFFERS_FIELD_CODE" => [
			0 => "",
			1 => "",
		],
		"OFFERS_PROPERTY_CODE" => [
			0 => "PROP2",
			1 => "COLOR",
			2 => "PROP3",
			3 => "",
		],
		"OFFERS_SORT_FIELD" => "sort",
		"OFFERS_SORT_ORDER" => "asc",
		"OFFERS_SORT_FIELD2" => "id",
		"OFFERS_SORT_ORDER2" => "asc",
		"OFFERS_LIMIT" => "",
		"PRICE_CODE" => [
		],
		"PRICE_VAT_INCLUDE" => "Y",
		"CONVERT_CURRENCY" => "N",
		"OFFERS_CART_PROPERTIES" => [
			0 => "PROP2",
		],
		"DISPLAY_IMG_WIDTH" => "250",
		"DISPLAY_IMG_HEIGHT" => "250",
		"ELEMENT_SORT_FIELD" => "RAND",
		"ELEMENT_SORT_ORDER" => "ASC",
		"DISPLAY_COMPARE" => "Y",
		"PROPERTY_CODE_MOD" => [
			0 => "",
			1 => "IN_STOCK",
			2 => "GUARANTEE",
			3 => "",
		],
		"HIDE_NOT_AVAILABLE" => "Y",
		"1CB_USE_FILE_FIELD" => "Y",
		"1CB_FILE_FIELD_MULTIPLE" => "Y",
		"1CB_FILE_FIELD_MAX_COUNT" => "5",
		"1CB_FILE_FIELD_NAME" => "Реквизиты",
		"1CB_FILE_FIELD_TYPE" => "doc, docx, txt, rtf",
		"1CB_REQUIRED_FIELDS" => [
			0 => "NAME",
			1 => "PHONE",
			2 => "EMAIL",
		],
		"USE_BIG_DATA" => "N",
		"BIG_DATA_RCM_TYPE" => "any",
		"COMPONENT_TEMPLATE" => ".default",
		"CORRECT_RATIO" => "Y",
		"AUTO_CALCULATION" => "Y",
		"USE_GIFTS" => "Y",
		"GIFTS_PLACE" => "",
		"GIFTS_BLOCK_TITLE" => "Выберите один из подарков",
		"GIFTS_HIDE_BLOCK_TITLE" => "N",
		"GIFTS_TEXT_LABEL_GIFT" => "",
		"GIFTS_PRODUCT_QUANTITY_VARIABLE" => "",
		"GIFTS_PRODUCT_PROPS_VARIABLE" => "",
		"GIFTS_SHOW_OLD_PRICE" => "",
		"GIFTS_SHOW_DISCOUNT_PERCENT" => "",
		"GIFTS_SHOW_NAME" => "",
		"GIFTS_SHOW_IMAGE" => "",
		"GIFTS_MESS_BTN_BUY" => "",
		"GIFTS_MESS_BTN_DETAIL" => "",
		"GIFTS_PAGE_ELEMENT_COUNT" => "",
		"GIFTS_CONVERT_CURRENCY" => "",
		"GIFTS_HIDE_NOT_AVAILABLE" => "",
		"COLUMNS_LIST_EXT" => [
			0 => "PREVIEW_PICTURE",
			1 => "DISCOUNT",
			2 => "DELETE",
			3 => "DELAY",
			4 => "TYPE",
			5 => "SUM",
			6 => "PROPERTY_IN_STOCK",
		],
		"COMPATIBLE_MODE" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"ADDITIONAL_PICT_PROP_15" => "-",
		"ADDITIONAL_PICT_PROP_16" => "-",
		"ADDITIONAL_PICT_PROP_24" => "-",
		"BASKET_IMAGES_SCALING" => "adaptive"
	],
	false
);?>

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
